'use strict';
const { commandRegistry } = require('../../../shared/cqrs');
const Post_rootCommand = require('./Post_rootCommand');
const Post_rootHandler = require('./Post_rootHandler');
commandRegistry.register('Post_rootCommand', new Post_rootHandler());
module.exports.Post_rootCommand = Post_rootCommand;
const Post_id_pdf_queueCommand = require('./Post_id_pdf_queueCommand');
const Post_id_pdf_queueHandler = require('./Post_id_pdf_queueHandler');
commandRegistry.register('Post_id_pdf_queueCommand', new Post_id_pdf_queueHandler());
module.exports.Post_id_pdf_queueCommand = Post_id_pdf_queueCommand;
const Post_id_emailCommand = require('./Post_id_emailCommand');
const Post_id_emailHandler = require('./Post_id_emailHandler');
commandRegistry.register('Post_id_emailCommand', new Post_id_emailHandler());
module.exports.Post_id_emailCommand = Post_id_emailCommand;
const Delete_idCommand = require('./Delete_idCommand');
const Delete_idHandler = require('./Delete_idHandler');
commandRegistry.register('Delete_idCommand', new Delete_idHandler());
module.exports.Delete_idCommand = Delete_idCommand;
require('../events');
