'use strict';
const { commandRegistry } = require('../../../shared/cqrs');
const Post_id_enrollmentsCommand = require('./Post_id_enrollmentsCommand');
const Post_id_enrollmentsHandler = require('./Post_id_enrollmentsHandler');
commandRegistry.register('Post_id_enrollmentsCommand', new Post_id_enrollmentsHandler());
module.exports.Post_id_enrollmentsCommand = Post_id_enrollmentsCommand;
const Put_id_enrollments_enrollmentId_settingsCommand = require('./Put_id_enrollments_enrollmentId_settingsCommand');
const Put_id_enrollments_enrollmentId_settingsHandler = require('./Put_id_enrollments_enrollmentId_settingsHandler');
commandRegistry.register('Put_id_enrollments_enrollmentId_settingsCommand', new Put_id_enrollments_enrollmentId_settingsHandler());
module.exports.Put_id_enrollments_enrollmentId_settingsCommand = Put_id_enrollments_enrollmentId_settingsCommand;
const Put_id_enrollments_enrollmentId_payCommand = require('./Put_id_enrollments_enrollmentId_payCommand');
const Put_id_enrollments_enrollmentId_payHandler = require('./Put_id_enrollments_enrollmentId_payHandler');
commandRegistry.register('Put_id_enrollments_enrollmentId_payCommand', new Put_id_enrollments_enrollmentId_payHandler());
module.exports.Put_id_enrollments_enrollmentId_payCommand = Put_id_enrollments_enrollmentId_payCommand;
const Delete_id_enrollments_enrollmentIdCommand = require('./Delete_id_enrollments_enrollmentIdCommand');
const Delete_id_enrollments_enrollmentIdHandler = require('./Delete_id_enrollments_enrollmentIdHandler');
commandRegistry.register('Delete_id_enrollments_enrollmentIdCommand', new Delete_id_enrollments_enrollmentIdHandler());
module.exports.Delete_id_enrollments_enrollmentIdCommand = Delete_id_enrollments_enrollmentIdCommand;
require('../events');
