'use strict';

/** Trạng thái phiên AI-support (Student/Teacher). Không dùng cho chat nội bộ Admin/Staff. */
const AI_SUPPORT_STATUS = Object.freeze({
  AI_ACTIVE: 'AI_ACTIVE',
  WAITING_FOR_SUPPORT: 'WAITING_FOR_SUPPORT',
  SUPPORT_ACTIVE: 'SUPPORT_ACTIVE',
  SUPPORT_RESOLVED: 'SUPPORT_RESOLVED',
  CLOSED: 'CLOSED',
});

const HANDOFF_REASONS = Object.freeze({
  USER_REQUESTED: 'USER_REQUESTED',
  AI_UNCERTAIN: 'AI_UNCERTAIN',
  REPEATED_FAILURE: 'REPEATED_FAILURE',
  ACCOUNT_ISSUE: 'ACCOUNT_ISSUE',
  PAYMENT_ISSUE: 'PAYMENT_ISSUE',
  ACCESS_ISSUE: 'ACCESS_ISSUE',
  TECHNICAL_ISSUE: 'TECHNICAL_ISSUE',
});

module.exports = {
  AI_SUPPORT_STATUS,
  HANDOFF_REASONS,
};
