/**
 * Standard Operational Audit Event definitions.
 */
const AuditEvents = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  PAYMENT_CREATED: 'PAYMENT_CREATED',
  PAYMENT_APPROVED: 'PAYMENT_APPROVED',
  REFUND_APPROVED: 'REFUND_APPROVED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  PERMISSION_CHANGED: 'PERMISSION_CHANGED',
  STUDENT_UPDATED: 'STUDENT_UPDATED',
  TEACHER_UPDATED: 'TEACHER_UPDATED',
  COURSE_ASSIGNED: 'COURSE_ASSIGNED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
};

module.exports = AuditEvents;
