'use strict';
const { commandRegistry } = require('../../../shared/cqrs');
const Post_importCommand = require('./Post_importCommand');
const Post_importHandler = require('./Post_importHandler');
commandRegistry.register('Post_importCommand', new Post_importHandler());
module.exports.Post_importCommand = Post_importCommand;
const Post_rootCommand = require('./Post_rootCommand');
const Post_rootHandler = require('./Post_rootHandler');
commandRegistry.register('Post_rootCommand', new Post_rootHandler());
module.exports.Post_rootCommand = Post_rootCommand;
const Put_idCommand = require('./Put_idCommand');
const Put_idHandler = require('./Put_idHandler');
commandRegistry.register('Put_idCommand', new Put_idHandler());
module.exports.Put_idCommand = Put_idCommand;
const Put_id_exam_progressCommand = require('./Put_id_exam_progressCommand');
const Put_id_exam_progressHandler = require('./Put_id_exam_progressHandler');
commandRegistry.register('Put_id_exam_progressCommand', new Put_id_exam_progressHandler());
module.exports.Put_id_exam_progressCommand = Put_id_exam_progressCommand;
const Patch_id_priceCommand = require('./Patch_id_priceCommand');
const Patch_id_priceHandler = require('./Patch_id_priceHandler');
commandRegistry.register('Patch_id_priceCommand', new Patch_id_priceHandler());
module.exports.Patch_id_priceCommand = Patch_id_priceCommand;
const Put_id_payCommand = require('./Put_id_payCommand');
const Put_id_payHandler = require('./Put_id_payHandler');
commandRegistry.register('Put_id_payCommand', new Put_id_payHandler());
module.exports.Put_id_payCommand = Put_id_payCommand;
const Put_id_refundCommand = require('./Put_id_refundCommand');
const Put_id_refundHandler = require('./Put_id_refundHandler');
commandRegistry.register('Put_id_refundCommand', new Put_id_refundHandler());
module.exports.Put_id_refundCommand = Put_id_refundCommand;
const Put_id_unlock_examCommand = require('./Put_id_unlock_examCommand');
const Put_id_unlock_examHandler = require('./Put_id_unlock_examHandler');
commandRegistry.register('Put_id_unlock_examCommand', new Put_id_unlock_examHandler());
module.exports.Put_id_unlock_examCommand = Put_id_unlock_examCommand;
const Put_id_lock_examCommand = require('./Put_id_lock_examCommand');
const Put_id_lock_examHandler = require('./Put_id_lock_examHandler');
commandRegistry.register('Put_id_lock_examCommand', new Put_id_lock_examHandler());
module.exports.Put_id_lock_examCommand = Put_id_lock_examCommand;
const Put_id_assign_teacherCommand = require('./Put_id_assign_teacherCommand');
const Put_id_assign_teacherHandler = require('./Put_id_assign_teacherHandler');
commandRegistry.register('Put_id_assign_teacherCommand', new Put_id_assign_teacherHandler());
module.exports.Put_id_assign_teacherCommand = Put_id_assign_teacherCommand;
const Delete_idCommand = require('./Delete_idCommand');
const Delete_idHandler = require('./Delete_idHandler');
commandRegistry.register('Delete_idCommand', new Delete_idHandler());
module.exports.Delete_idCommand = Delete_idCommand;
const Post_id_reset_today_attendanceCommand = require('./Post_id_reset_today_attendanceCommand');
const Post_id_reset_today_attendanceHandler = require('./Post_id_reset_today_attendanceHandler');
commandRegistry.register('Post_id_reset_today_attendanceCommand', new Post_id_reset_today_attendanceHandler());
module.exports.Post_id_reset_today_attendanceCommand = Post_id_reset_today_attendanceCommand;
const Post_id_reset_historyCommand = require('./Post_id_reset_historyCommand');
const Post_id_reset_historyHandler = require('./Post_id_reset_historyHandler');
commandRegistry.register('Post_id_reset_historyCommand', new Post_id_reset_historyHandler());
module.exports.Post_id_reset_historyCommand = Post_id_reset_historyCommand;
const Put_id_pay_teacherCommand = require('./Put_id_pay_teacherCommand');
const Put_id_pay_teacherHandler = require('./Put_id_pay_teacherHandler');
commandRegistry.register('Put_id_pay_teacherCommand', new Put_id_pay_teacherHandler());
module.exports.Put_id_pay_teacherCommand = Put_id_pay_teacherCommand;
require('../events');
