'use strict';
const { commandRegistry } = require('../../../shared/cqrs');
const Post_rootCommand = require('./Post_rootCommand');
const Post_rootHandler = require('./Post_rootHandler');
commandRegistry.register('Post_rootCommand', new Post_rootHandler());
module.exports.Post_rootCommand = Post_rootCommand;
const Put_scheduleIdCommand = require('./Put_scheduleIdCommand');
const Put_scheduleIdHandler = require('./Put_scheduleIdHandler');
commandRegistry.register('Put_scheduleIdCommand', new Put_scheduleIdHandler());
module.exports.Put_scheduleIdCommand = Put_scheduleIdCommand;
const Delete_scheduleIdCommand = require('./Delete_scheduleIdCommand');
const Delete_scheduleIdHandler = require('./Delete_scheduleIdHandler');
commandRegistry.register('Delete_scheduleIdCommand', new Delete_scheduleIdHandler());
module.exports.Delete_scheduleIdCommand = Delete_scheduleIdCommand;
const Patch_scheduleId_cancelCommand = require('./Patch_scheduleId_cancelCommand');
const Patch_scheduleId_cancelHandler = require('./Patch_scheduleId_cancelHandler');
commandRegistry.register('Patch_scheduleId_cancelCommand', new Patch_scheduleId_cancelHandler());
module.exports.Patch_scheduleId_cancelCommand = Patch_scheduleId_cancelCommand;
require('../events');
