'use strict';
const { commandRegistry } = require('../../../shared/cqrs');
const Post_uploadCommand = require('./Post_uploadCommand');
const Post_uploadHandler = require('./Post_uploadHandler');
commandRegistry.register('Post_uploadCommand', new Post_uploadHandler());
module.exports.Post_uploadCommand = Post_uploadCommand;
const Post_rootCommand = require('./Post_rootCommand');
const Post_rootHandler = require('./Post_rootHandler');
commandRegistry.register('Post_rootCommand', new Post_rootHandler());
module.exports.Post_rootCommand = Post_rootCommand;
const Put_idCommand = require('./Put_idCommand');
const Put_idHandler = require('./Put_idHandler');
commandRegistry.register('Put_idCommand', new Put_idHandler());
module.exports.Put_idCommand = Put_idCommand;
const Delete_idCommand = require('./Delete_idCommand');
const Delete_idHandler = require('./Delete_idHandler');
commandRegistry.register('Delete_idCommand', new Delete_idHandler());
module.exports.Delete_idCommand = Delete_idCommand;
const Post_id_submitCommand = require('./Post_id_submitCommand');
const Post_id_submitHandler = require('./Post_id_submitHandler');
commandRegistry.register('Post_id_submitCommand', new Post_id_submitHandler());
module.exports.Post_id_submitCommand = Post_id_submitCommand;
const Put_submissions_submissionId_gradeCommand = require('./Put_submissions_submissionId_gradeCommand');
const Put_submissions_submissionId_gradeHandler = require('./Put_submissions_submissionId_gradeHandler');
commandRegistry.register('Put_submissions_submissionId_gradeCommand', new Put_submissions_submissionId_gradeHandler());
module.exports.Put_submissions_submissionId_gradeCommand = Put_submissions_submissionId_gradeCommand;
require('../events');
