'use strict';
const { commandRegistry } = require('../../../shared/cqrs');
const Post_calculateCommand = require('./Post_calculateCommand');
const Post_calculateHandler = require('./Post_calculateHandler');
commandRegistry.register('Post_calculateCommand', new Post_calculateHandler());
module.exports.Post_calculateCommand = Post_calculateCommand;
const Post_rootCommand = require('./Post_rootCommand');
const Post_rootHandler = require('./Post_rootHandler');
commandRegistry.register('Post_rootCommand', new Post_rootHandler());
module.exports.Post_rootCommand = Post_rootCommand;
const Put_id_confirmCommand = require('./Put_id_confirmCommand');
const Put_id_confirmHandler = require('./Put_id_confirmHandler');
commandRegistry.register('Put_id_confirmCommand', new Put_id_confirmHandler());
module.exports.Put_id_confirmCommand = Put_id_confirmCommand;
const Put_id_cancelCommand = require('./Put_id_cancelCommand');
const Put_id_cancelHandler = require('./Put_id_cancelHandler');
commandRegistry.register('Put_id_cancelCommand', new Put_id_cancelHandler());
module.exports.Put_id_cancelCommand = Put_id_cancelCommand;
const Delete_idCommand = require('./Delete_idCommand');
const Delete_idHandler = require('./Delete_idHandler');
commandRegistry.register('Delete_idCommand', new Delete_idHandler());
module.exports.Delete_idCommand = Delete_idCommand;
require('../events');
