'use strict';
const { commandRegistry } = require('../../../shared/cqrs');
const CreateTeacherCommand = require('./CreateTeacherCommand');
const CreateTeacherHandler = require('./CreateTeacherHandler');
commandRegistry.register('CreateTeacherCommand', new CreateTeacherHandler());
module.exports.CreateTeacherCommand = CreateTeacherCommand;
const Put_idCommand = require('./Put_idCommand');
const Put_idHandler = require('./Put_idHandler');
commandRegistry.register('Put_idCommand', new Put_idHandler());
module.exports.Put_idCommand = Put_idCommand;
const Delete_idCommand = require('./Delete_idCommand');
const Delete_idHandler = require('./Delete_idHandler');
commandRegistry.register('Delete_idCommand', new Delete_idHandler());
module.exports.Delete_idCommand = Delete_idCommand;
const Post_id_payCommand = require('./Post_id_payCommand');
const Post_id_payHandler = require('./Post_id_payHandler');
commandRegistry.register('Post_id_payCommand', new Post_id_payHandler());
module.exports.Post_id_payCommand = Post_id_payCommand;
require('../events');
